=== kaizenchandra/app365/specs/schemas/accountResponse-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "subdomain",
    "firstName",
    "lastName"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "candidateId": {
      "type": "string"
    },
    "subdomain": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "phoneCountryCode": {
      "type": "string"
    },
    "candidateFor": {
      "type": "string"
    },
    "configuration": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "crm": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "baseUrl": {
              "type": "string"
            },
            "idCardRequireDashes": {
              "type": "boolean"
            }
          }
        }
      }
    }
  }
}

=== kaizenchandra/app365/specs/examples/accountResponse-example.json
{
  "id": "f4854665-ab24-4c27-b4f1-b51a90ccae83",
  "candidateId": "b4449c79-8dab-45e6-821a-d669a86e30ff",
  "subdomain": "maxcredi",
  "firstName": "Shanna",
  "lastName": "Booker",
  "email": "beckblack@syntac.com",
  "phone": "8585463680",
  "phoneCountryCode": "1",
  "candidateFor": "President",
  "configuration": {
    "crm": {
      "baseUrl": "http://192.168.1.200:8090/api/v1",
      "idCardRequireDashes": true
    }
  }
}
