=== kaizenchandra/app365/specs/schemas/candidateInfoResponse-schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "fullName": {
      "type": "string"
    },
    "profilePicture": {
      "type": "string"
    },
    "party": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "nameAbbr": {
          "type": "string"
        },
        "bannerPicture": {
          "type": "string"
        },
        "slogan": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "summary": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "donationCount": {
          "type": "integer"
        },
        "offerCount": {
          "type": "integer"
        },
        "shareCount": {
          "type": "integer"
        },
        "commentCount": {
          "type": "integer"
        },
        "likeCount": {
          "type": "integer"
        },
        "postCount": {
          "type": "integer"
        },
        "postCommentCount": {
          "type": "integer"
        }
      }
    },
    "bio": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        }
      }
    },
    "meta": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lastComment": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string"
            },
            "content": {
              "type": "string"
            },
            "createdAt": {
              "type": "string"
            },
            "owner": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "string"
                },
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                },
                "fullName": {
                  "type": "string"
                },
                "nickname": {
                  "type": "string"
                },
                "profilePicture": {
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "id",
            "content",
            "createdAt",
            "owner"
          ]
        },
        "user": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "liked": {
              "type": "boolean"
            },
            "commented": {
              "type": "boolean"
            },
            "shared": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "required": [
    "id",
    "firstName",
    "lastName",
    "fullName"
  ]
}

=== kaizenchandra/app365/specs/examples/candidateInfoResponse-example.json
{
  "id": "8bfa4c24-a236-4f96-ba18-fa748597e528",
  "firstName": "Mathis",
  "lastName": "Campos",
  "fullName": "Mathis Campos",
  "profilePicture": "http://placehold.it/400x300",
  "party": {
    "name": "irure adipisicing magna",
    "nameAbbr": "IAM",
    "bannerPicture": "http://placehold.it/400x300",
    "slogan": "officia voluptate ad anim"
  },
  "summary": {
    "donationCount": 31,
    "offerCount": 31,
    "shareCount": 68,
    "commentCount": 38,
    "likeCount": 80,
    "postCount": 59,
    "postCommentCount": 48
  },
  "bio": {
    "description": "Esse ipsum labore minim ea ut reprehenderit occaecat qui aliquip. Sit enim mollit culpa laboris minim deserunt. Aliqua do exercitation enim sunt voluptate incididunt fugiat mollit ut. Sunt ex ea quis proident. Occaecat ut sint laboris velit aliquip cillum ex eiusmod eiusmod qui. Aliquip non tempor nisi voluptate exercitation dolor dolore culpa ipsum consectetur. Pariatur amet amet reprehenderit tempor sint consectetur Lorem laboris laboris anim aliquip veniam cupidatat.\r\nIpsum exercitation sit id qui aliquip cupidatat. Eiusmod et mollit reprehenderit ad exercitation nulla commodo adipisicing elit nisi irure. Esse velit sint incididunt aute nostrud amet adipisicing. Laboris reprehenderit exercitation eiusmod mollit cillum nulla ea proident tempor non fugiat nisi voluptate. Labore quis reprehenderit nostrud dolor do nisi ad esse eu aute incididunt ad. Esse esse nulla duis amet amet deserunt irure pariatur nulla minim laboris pariatur dolor eu.\r\nVeniam sit cupidatat magna cillum ipsum duis in duis officia labore. Voluptate sit incididunt mollit incididunt labore sit nulla ea commodo et laborum. Laborum cupidatat Lorem aute sunt eu fugiat sit culpa. Aute deserunt nulla exercitation laboris Lorem amet et ullamco cupidatat. Laborum proident reprehenderit ex do amet sit sit. Et sint id aliquip ipsum anim. Veniam officia amet laboris pariatur deserunt pariatur officia ea dolore deserunt aute nulla cupidatat.\r\n"
  },
  "meta": {
    "lastComment": {
      "id": "83de2388-a8fc-493f-b392-0fe640fc5aa6",
      "content": "Elit fugiat cupidatat exercitation non voluptate incididunt pariatur ad esse enim ea ut. Sit id excepteur fugiat tempor duis adipisicing. Quis cupidatat id incididunt commodo.",
      "createdAt": "2018-08-31T11:22:40+04:00",
      "owner": {
        "id": "a373d936-b051-410e-b8d6-9c3d967a5fa7",
        "firstName": "Louella",
        "lastName": "Mueller",
        "fullName": "Louella Mueller",
        "nickname": "Louella",
        "profilePicture": "http://placehold.it/400x300"
      }
    },
    "user": {
      "liked": true,
      "commented": true,
      "shared": false
    }
  }
}
