=== kaizenchandra/app365/specs/schemas/electoralRollVoterResponse-schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "idCard": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "fullName": {
      "type": "string"
    },
    "profilePicture": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "country": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "municipality": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "sector": {
          "type": "string"
        },
        "line1": {
          "type": "string"
        },
        "line2": {
          "type": "string"
        },
        "zipCode": {
          "type": "string"
        },
        "reference": {
          "type": "string"
        },
        "fullAddress": {
          "type": "string"
        }
      },
      "required": [
        "country",
        "city",
        "line1"
      ]
    }
  },
  "required": [
    "idCard",
    "firstName",
    "lastName",
    "address"
  ]
}

=== kaizenchandra/app365/specs/examples/electoralRollVoterResponse-example.json
{
  "idCard": "123-2985101-8",
  "firstName": "Greer",
  "lastName": "Bernard",
  "fullName": "Greer Bernard",
  "profilePicture": "http://placehold.it/400x300",
  "address": {
    "country": "Gambia",
    "state": "Connecticut",
    "municipality": "Nebraska",
    "city": "Boyd",
    "sector": "Greensburg",
    "line1": "Drummond",
    "line2": "Opal Court",
    "zipCode": "609",
    "reference": "Crown Street",
    "fullAddress": "502 Gilmore Court, Tampico, Arkansas, 1630"
  }
}
