=== kaizenchandra/app365/specs/schemas/electoralCollegeResponse-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "name"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "code": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "picture": {
      "type": "string"
    },
    "location": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "geo": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lat",
            "lon"
          ],
          "properties": {
            "lat": {
              "type": "number"
            },
            "lon": {
              "type": "number"
            }
          }
        }
      }
    }
  }
}

=== kaizenchandra/app365/specs/examples/electoralCollegeResponse-example.json
{
  "id": "0247c08e-3c1f-4fcd-94f1-cb014bcca4e7",
  "code": "0034",
  "name": "Bawcomville",
  "picture": "https://placeimg.com/640/480/tech?t=2340826043",
  "location": {
    "address": "515 Kay Court, Bellamy, Federated States Of Micronesia, 8830",
    "geo": {
      "lat": 13.634357,
      "lon": -108.36603
    }
  }
}
