=== kaizenchandra/app365/specs/schemas/medalResponse-schema.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "picture": {
      "type": "string"
    },
    "point": {
      "type": "integer"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "instructions": {
      "type": "string"
    },
    "benefits": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "name",
    "description",
    "picture",
    "point",
    "createdAt",
    "instructions",
    "benefits"
  ]
}

=== kaizenchandra/app365/specs/examples/medalResponse-example.json
{
  "id": "df22f2ca-0583-46ee-bb3f-ed628df8ae49",
  "name": "ad",
  "description": "Minim nisi nostrud amet anim minim aliqua cillum amet consequat occaecat cupidatat fugiat consequat velit.",
  "picture": "http://placehold.it/400x300",
  "point": 32,
  "createdAt": "2019-07-01T08:03:38+04:00",
  "instructions": "Cupidatat sunt proident adipisicing magna voluptate magna commodo esse occaecat occaecat minim adipisicing.",
  "benefits": "Ea sit et ad deserunt labore sint incididunt. Eiusmod ut ut tempor nostrud veniam ex aute veniam eiusmod cillum veniam veniam velit ea. Tempor nostrud culpa anim eiusmod. Nulla id id veniam est ea dolore qui enim ad. Exercitation do sunt proident dolore velit ad est minim ad dolor."
}
