=== kaizenchandra/app365/specs/schemas/slides-schema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "The slide id"
      },
      "title": {
        "type": "string",
        "description": "Slide title"
      },
      "description": {
        "type": "string",
        "description": "Slide description text"
      },
      "image": {
        "type": "string",
        "description": "Slide image url"
      }
    },
    "required": [
      "id",
      "title",
      "description",
      "image"
    ]
  }
}

=== kaizenchandra/app365/specs/examples/slidesResponse-example.json
[
  {
    "id": "a0b4ed85-b1b5-46c1-97b1-46c855ae3d2d",
    "title": "magna veniam sit",
    "description": "Veniam nostrud proident irure esse magna deserunt aute nulla.",
    "image": "http://placehold.it/400x300"
  },
  {
    "id": "090fb252-648c-4492-80c0-5665111893db",
    "title": "labore laboris non",
    "description": "Commodo dolor sunt eu veniam aliqua non aliquip ad et.",
    "image": "http://placehold.it/400x300"
  },
  {
    "id": "839b3c82-16c9-4648-9e59-0809382ef09a",
    "title": "laborum amet sunt",
    "description": "Quis labore eiusmod ut enim minim excepteur amet ea sunt commodo aliquip nisi duis.",
    "image": "http://placehold.it/400x300"
  }
]
