=== kaizenchandra/app365/specs/schemas/teamMemberAddressPatchRequest-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "country": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "string"
        }
      }
    },
    "state": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "municipality": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "city": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "sector": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "street": {
      "type": "string"
    },
    "home": {
      "type": "string"
    },
    "apartment": {
      "type": "string"
    },
    "zipCode": {
      "type": "string"
    },
    "reference": {
      "type": "string"
    }
  }
}

=== kaizenchandra/app365/specs/examples/teamMemberAddressPatchRequest-example.json
{
  "country": {
    "id": ""
  },
  "state": {
    "id": "",
    "name": ""
  },
  "municipality": {
    "id": "",
    "name": ""
  },
  "city": {
    "id": "",
    "name": ""
  },
  "sector": {
    "id": "",
    "name": ""
  },
  "street": "Manzana AA",
  "home": "4",
  "apartment": "B",
  "zipCode": "12345",
  "reference": ""
}
