=== kaizenchandra/app365/specs/schemas/userResponse-schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "id": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "fullName": {
      "type": "string"
    },
    "nickname": {
      "type": "string"
    },
    "idCard": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "phoneCountryCode": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "profilePicture": {
      "type": "string"
    },
    "birthDate": {
      "type": "string",
      "format": "date"
    },
    "age": {
      "type": "integer"
    },
    "channel": {
      "type": "string"
    },
    "verified": {
      "type": "boolean"
    },
    "timeZoneOffset": {
      "type": "integer"
    },
    "timeZone": {
      "type": "string"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "language": {
      "type": "string"
    },
    "meta": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "socialTokens"
      ],
      "properties": {
        "socialTokens": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "channel"
            ],
            "properties": {
              "channel": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "awards": {
      "type": "object",
      "properties": {
        "points": {
          "type": "integer"
        },
        "medals": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "image": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name",
              "description",
              "image"
            ]
          }
        }
      },
      "required": [
        "points",
        "medals"
      ]
    },
    "address": {
      "type": "object",
      "properties": {
        "country": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "iso2": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "iso2",
            "name"
          ]
        },
        "state": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        },
        "municipality": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        },
        "city": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        },
        "sector": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        },
        "line": {
          "type": "string"
        },
        "street": {
          "type": "string"
        },
        "home": {
          "type": "string"
        },
        "apartment": {
          "type": "string"
        },
        "reference": {
          "type": "string"
        },
        "fullAddress": {
          "type": "string"
        }
      },
      "required": [
        "country",
        "state",
        "city",
        "street",
        "home"
      ]
    }
  },
  "required": [
    "id",
    "firstName",
    "lastName",
    "channel"
  ]
}

=== kaizenchandra/app365/specs/examples/userResponse-example.json
{
  "id": "d8a51ea5-56c0-4f83-90b0-b6c29012e047",
  "firstName": "John",
  "lastName": "Doe",
  "fullName": "John Doe",
  "nickname": "John",
  "idCard": "123-4567890-2",
  "email": "john.doe@gmail.com",
  "phoneCountryCode": "1",
  "phone": "+1 (954) 314-1234",
  "profilePicture": "http://placehold.it/400x300",
  "birthDate": "1986-07-15",
  "age": 31,
  "channel": "applepolitical",
  "verified": true,
  "timeZoneOffset": -25200,
  "timeZone": "America/Santo_Domingo",
  "createdAt": "2019-07-01T08:03:38+04:00",
  "language": "en",
  "meta": {
    "socialTokens": [
      {
        "channel": "facebook"
      }
    ]
  },
  "awards": {
    "points": 50,
    "medals": [
      {
        "id": "",
        "name": "",
        "description": "",
        "image": ""
      }
    ]
  },
  "address": {
    "country": {
      "id": "",
      "iso2": "DO",
      "name": "Dominican Republic"
    },
    "state": {
      "id": "",
      "name": "Santiago"
    },
    "municipality": {
      "id": "",
      "name": "Santiago de los Caballeros"
    },
    "city": {
      "id": "",
      "name": "Santiago"
    },
    "sector": {
      "id": "",
      "name": "Villa Olimpica"
    },
    "line": "Manzana AA, Apto 4A",
    "street": "C/Profesor Jose Miralles",
    "home": "B",
    "apartment": "3",
    "zipCode": "12345",
    "reference": "",
    "fullAddress": ""
  }
}
