=== kaizenchandra/app365/specs/schemas/userPatchRequest-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "additionalProperties": false,
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "nickname": {
      "type": "string"
    },
    "idCard": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "country": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id"
          ],
          "properties": {
            "id": {
              "type": "string"
            }
          }
        },
        "state": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        "municipality": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        "city": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        "sector": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        "street": {
          "type": "string"
        },
        "home": {
          "type": "string"
        },
        "apartment": {
          "type": "string"
        },
        "zipCode": {
          "type": "string"
        },
        "reference": {
          "type": "string"
        }
      }
    }
  }
}

=== kaizenchandra/app365/specs/examples/userPatchRequest-example.json
{
  "firstName": "John",
  "lastName": "Doe",
  "nickname": "John",
  "idCard": "123-4567890-2",
  "email": "john.doe@gmail.com",
  "phone": "+1 (954) 314-1234",
  "address": {
    "country": {
      "id": ""
    },
    "state": {
      "id": "",
      "name": ""
    },
    "municipality": {
      "id": "",
      "name": ""
    },
    "city": {
      "id": "",
      "name": ""
    },
    "sector": {
      "id": "",
      "name": ""
    },
    "street": "Manzana AA",
    "home": "4",
    "apartment": "B",
    "zipCode": "12345",
    "reference": ""
  }
}
