=== kaizenchandra/app365/specs/schemas/videoResponse-schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "thumbnail": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "summary": {
      "type": "object",
      "properties": {
        "shareCount": {
          "type": "integer"
        },
        "commentCount": {
          "type": "integer"
        },
        "likeCount": {
          "type": "integer"
        }
      },
      "required": [
        "shareCount",
        "commentCount",
        "likeCount"
      ]
    },
    "owner": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "fullName": {
          "type": "string"
        },
        "nickname": {
          "type": "string"
        },
        "profilePicture": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "fullName",
        "profilePicture"
      ]
    }
  },
  "required": [
    "id",
    "title",
    "content",
    "createdAt",
    "thumbnail",
    "summary",
    "owner"
  ]
}

=== kaizenchandra/app365/specs/examples/videoResponse-example.json
{
  "id": "a6a2d3db-f434-400d-a534-f9d7a68a4a96",
  "title": "consequat dolor est culpa anim quis cupidatat non",
  "content": "Adipisicing aute duis dolor pariatur ad. Irure nisi sunt est velit nostrud consequat aliqua nostrud. Sunt amet deserunt ea nisi quis non nisi quis commodo ullamco id. Aute cupidatat consequat id irure et anim irure. Aliqua anim sit aliquip nisi fugiat. Magna elit anim cupidatat ea pariatur cupidatat eu ea sit eu Lorem.\r\nEsse ex veniam dolor commodo sint. Anim dolor laboris adipisicing laborum deserunt est enim nisi voluptate adipisicing. Esse duis mollit veniam consectetur est elit enim tempor reprehenderit occaecat ad adipisicing quis. Sint aliquip do reprehenderit Lorem duis voluptate consequat amet ex do. Ad anim ut commodo officia qui non et elit anim cillum.\r\n",
  "createdAt": "2018-07-26T09:12:57+04:00",
  "thumbnail": "http://placehold.it/400x300",
  "url": "http://placehold.it/400x300",
  "summary": {
    "shareCount": 8,
    "commentCount": 65,
    "likeCount": 95
  },
  "owner": {
    "id": "a5d80464-336f-47ab-b63d-129749bfbf4f",
    "firstName": "Nadine",
    "lastName": "Travis",
    "fullName": "Nadine Travis",
    "nickname": "Nadine",
    "profilePicture": "http://placehold.it/400x300"
  }
}
